version: "3.3"

services:

  app:
    image: gmlpdou/spring-app-vault:${TAG:-latest}
    ports:
      - 8082:8080
    networks:
      - default
      - vault
    configs:
      - bootstrap.yaml
    environment:
      - VAULT_TOKEN=root
    deploy:
      resources:
        reservations:
          memory: 200M
        limits:
          memory: 300M

  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    networks:
      - default
      - vault
    deploy:
      resources:
        reservations:
          memory: 200M
        limits:
          memory: 300M

networks:
  default:
    external: false
  vault:
    external: true

configs:
  bootstrap.yaml:
    file: ./config/bootstrap.yaml