version: "3.3"

services:

  vault:
    image: vault:0.11.5
    ports:
      - 127.0.0.1:8200:8200
    networks:
      - vault 
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=root

networks:
  vault:
    external: true 